site_name: mljar-docs
pages:
- Home: index.md
- Quick Start: usage.md
- Python API: python.md
- Data Formats: data.md
theme: readthedocs
site_url: https://www.mljar.com
copyright: Copyright 2016 mljar
